#!/usr/bin/env ruby
#
# SMELL:  brew leaves is not reliable; or maybe
#         it is being used the wrong way.
#

require 'amazing_print'
require 'debug_me'
include DebugMe

require 'pathname'
require 'set'

# TODO: Add some usage text

me      = Pathname.new(__FILE__).realpath
my_name = me.basename
my_dir  = me.parent

brewfile_name = 'Brewfile'

USAGE = <<~END_USAGE

  Usage: #{my_name} [path_to_brewfile]

  TODO: Add some usage text

END_USAGE


if ARGV.empty?
  brewfile_path = Pathname.pwd + brewfile_name
else
  bf_path = Pathname.new(ARGV.shift)
  if bf_path.exist?
    if bf_path.directory?
      brewfile_path = bf_path + brewfile_name
      unless brewfile_path.exist?
        puts <<~ERROR

          Error: File does not exist:  #{brewfile_path}

        ERROR
        exit(-1)
      end
    else
      brewfile_path = bf_path
    end
  else
    puts <<~ERROR

      Error: Pathgiven does not exist: #{bf_path}

    ERROR
    exit(-1)
  end
end


installed = `brew leaves -r`.split("\n").map{|f| f.strip}.sort

bfh = Hash.new

brewfile_path.
  read.
  split("\n").
  select{|a_line| !a_line.empty? && !a_line.start_with?('#')}.
  each do |a_line|
    key       = a_line.split(' ').first.strip
    bfh[key]  = a_line
  end

bfh_keys          = bfh.keys.sort

installed_set     = installed.to_set
not_installed_set = bfh_keys.to_set - installed_set

not_installed_set.each do |package|
  puts "#{bfh[package]}"
end

puts "="*65

not_installed = (bfh_keys - installed)

ap not_installed

File.open('bfh_keys.txt', 'w').write bfh_keys.join("\n")
File.open('installed.txt', 'w').write installed.join("\n")

if ARGV.include? "--install"
  puts "Installing ..."

  not_installed.each_slice(5) do |group|
    command = "brew install #{group.join(' ')}"
    puts command
    `#{command}`
  end
end
