#!/usr/bin/env ruby
##########################################
###
##  File: gemt
##  Desc: Build gem install command
##
##  Input is STDIN a list of gem names, 1 per line
#

require 'awesome_print'

class NilClass
  def split(*args)
    [" "]
  end
  def strip
    ""
  end
end

gem_hash = Hash.new

desc_start_col = 30

Gem::Specification.all.each do |gs|
  gem_hash[gs.name] = gs.summary
end

gem_hash.each_pair do |k, v|
  print "#{k}  "
  spacer_cnt = desc_start_col - k.length
  spacer_cnt = 1 if spacer_cnt <= 0
  print " "*spacer_cnt
  puts v.split("\n").first.strip
end

# ap Gem::Specification.all.first.instance_variables

