#!/usr/bin/env ruby
##########################################
###
##  File: gemt
##  Desc: Like "rake -T"
##
#

require 'awesome_print'
require 'terminal-size'
require 'word_wrapper'

def usage
  puts <<-EOS

list gems -- like "rake -T"

usage: #{__FILE__.basename} [search_string]

Where:

  search_string is an optional keyword or phrase

Example:

  gemt guard      shows list of the guard gems

EOS
end

class NilClass
  def split(*args)
    [" "]
  end
  def strip
    ""
  end
end

search_string = nil

unless ARGV.empty?
  if '-h' == ARGV.first  or  '--help' == ARGV.first
    usage
    exit
  end
  search_string = ARGV.join(' ').downcase
end

gem_hash = Hash.new

longest_desc = 0

Gem::Specification.all.each do |gs|
  if search_string
    thing = (gs.name + ' ' + gs.summary).downcase
    next unless thing.include?(search_string)
  end
  gem_hash[gs.name] = gs.summary
  longest_desc = gs.name.size if longest_desc < gs.name.size
end

desc_start_col = longest_desc + 2

width = Terminal.size[:width] - desc_start_col

gem_hash.each_pair do |k, v|
  print "#{k}"
  print " "*(desc_start_col - k.size)
  text = WordWrapper::MinimumRaggedness.new(width, v.split("\n").first.strip).wrap
  text += "https://rubygems.org/gems/#{k}"
  text_array = text.split("\n")
  text_array.each_index do |x|
    puts (x<1 ? text_array[x] : (' '*desc_start_col) + '|__ '+text_array[x] )
  end
end

# ap Gem::Specification.all.first.instance_variables

