#!/usr/bin/env ruby
##########################################
###
##  File: fav.rb
##  Desc: Build gem install command
##
##  Input is STDIN a list of gem names, 1 per line
#

require 'awesome_print'
require 'systemu'

if ARGV.length > 0

  ARGV.each do |gem_name|
    puts systemu("gem list #{gem_name} --details")[1]
  end

else

  full_list_gems = systemu("gem list --details")[1].split("\n\n")

  gem_desc = Hash.new
  last_gem = "unknown"

  full_list_gems.each do |g|

    if g.include?("Author")
      gem_name = g.split(" ").first
      gem_desc[gem_name]="unk"
      last_gem = gem_name
    else
      #puts "\t"+g
      gem_desc[last_gem] = g.strip
    end

  end

  ap gem_desc

end
