#!/usr/bin/env ruby
# encoding: utf-8
##########################################################
###
##  File: json
##  Desc: Pretty-print a JSON file
##  By:   Dewayne VanHoozer (dvanhoozer@gmail.com)
#
#   The JSON file can have some not JSON header material.
#   The file can be one JSON object or a series of JSON objects (events)
#   where each line in the file is a JSON event.
#
# TODO:   Refactor this program
#

require 'pathname'
require 'json'


def show_usage
  puts <<~EOS

  pretty prints JSON files

  Usage: #{Pathname.new(__FILE__).basebane} json_files+

  Where:

    json_files+ is one or more *.json file paths

  EOS

  exit
end

# Display the usage info
if  ARGV.empty?
  show_usage
  exit
end

paths = ARGV.map do |a|
  a_path = Pathname.new(a)
  if  ! a_path.exist? ||
      ! ['.log', '.json', '.jsonl'].include?(a_path.extname.to_s.downcase)
    STDERR.puts "ERROR: Not a valid JSON file '#{a_path}'"
    a_path = nil
  end
  a_path
end.compact

exit if paths.empty?


######################################################
# Local methods

def pretty_print_json(text)
  puts JSON.pretty_generate( JSON.parse(text) )
end

def pretty_print_jsonl(content)
  record_counter = 0

  content.each_line do |line|
    line = line.strip
    next if line.empty?

    record_counter += 1
    puts
    puts "## Record: #{record_counter}"
    puts

    begin
      pretty_print_json(line)
    rescue JSON::ParserError => e
      STDERR.puts "WARNING: Record #{record_counter} is not valid JSON -- #{e.message}"
      puts line
    end
  end
end

def print_file(a_path)
  puts
  puts "#"*65
  puts "## File: #{a_path}"
  puts

  content = a_path.read

  begin
    pretty_print_json(content)
  rescue JSON::ParserError
    pretty_print_jsonl(content)
  end
end

######################################################
# Main

at_exit do
  puts
  puts "Done."
  puts
end

paths.each do |a_path|
  print_file(a_path)
end
