#!/usr/bin/env ruby
# encoding: utf-8
##########################################################
###
##  File: json
##  Desc: Pretty-print a JSON file
##  By:   Dewayne VanHoozer (dvanhoozer@gmail.com)
#

require 'awesome_print'

require 'json'
require 'cli_helper'
include CliHelper

configatron.version = '0.0.1'

HELP = <<EOHELP
Parameters

  JSON_FILE++  One of more JSON files
EOHELP

cli_helper("Pretty print JSON files") do |o|
  o.bool '-e', '--edit', 'make json more easily edited'
end

# Display the usage info
if  ARGV.empty?
  show_usage
  exit
end

configatron.arguments.map!{|p| Pathname.new(p)}

configatron.arguments.each_index do |x|
  p = configatron.arguments[x]
  unless '.json' == p.extname.to_s.downcase
    warning "Not a valid JSON file '#{p}'"
    configatron.arguments[x] = nil
  end
end

configatron.arguments.compact!

if configatron.arguments.empty?
  error 'no JSON files were specified'
end

abort_if_errors


######################################################
# Local methods


######################################################
# Main

at_exit do
  puts
  puts "Done."
  puts
end

ap configatron.to_h  if verbose? || debug?

configatron.arguments.each do |p|
  if edit?
    puts JSON.pretty_generate(JSON.parse(p.read))
  else
    puts "="*45
    puts "== File: #{p}"
    ap JSON.parse(p.read)
  end
end
