#!/usr/bin/env ruby
####################################################
###
##  File: rtags
##  Desc: Generates .tags file for ruby code for use
##        withing Sublime Text and other utilities
##
#   gem install ripper-tags
#

`ripper-tags -R --tag-file=.tags .`
