#!/usr/bin/env ruby
####################################################
###
##  File: rtags
##  Desc: Generates .tags file for ruby code for use
##        withing Sublime Text and other utilities
#

system "find . -name '*.rb' | ctags #{ARGV.join(' ')} -u -f .tags -L -"

if File.exist? './Gemfile'
  require 'bundler'
  paths = Bundler.load.specs.map(&:full_gem_path).join(' ')
  system "ctags -R -f .gemtags #{paths}"
end
