#!/usr/bin/env ruby

require 'terminal-size'

width   = Terminal.size[:width]
height  = Terminal.size[:height]
dots    = "."*(width+10)
tens    = (1..width).step(10).map {|x| x-1}
fives   = tens.map{|x|x+5}

tens.shift

tens.each do |x|
  y = x/100 + 1
  dots[x-y,y]=(x/10).to_s
end

fives.each{|x| dots[x-1]='^'}

puts "Terminal Size: #{height} rows by #{width} columns"
puts dots[0,width]

