#!/usr/bin/env ruby
########################################
## xmlpp

require 'nokogiri'
require 'pathname'



if ARGV.empty?
  puts "\nERROR: need an XML file as a parameter."
  exit(-1)
end

file_path = Pathname.new ARGV.shift

unless file_path.exist?
  puts "\nERROR: File does not exist.  #{file_path}"
  exit(-1)
end

xml_doc = Nokogiri::XML(file_path.read) { |config| config.strict }

puts xml_doc.to_xml(indent: 2, encoding: 'UTF-8')
