# Rakefile


require 'amazing_print'
require 'require_all'
require 'table_print'


require_relative 'app'

module Rails
  class << self
    def root
      ROOT
    end
  end
end


require "sinatra/activerecord/rake"


require_all "./tasks"
